version: "2"

run:
  timeout: 5m
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - errorlint
    - nilerr
    - bodyclose
    - copyloopvar
    - noctx
    - nolintlint
    - misspell
    - whitespace
